# This is a config for E2B sandbox template.
# You can use template ID (iq83b9fpyvdnsolrt9n9) or template name (crafideeee-nextjs-new2-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("crafideeee-nextjs-new2-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("crafideeee-nextjs-new2-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('crafideeee-nextjs-new2-2')

team_id = "eddb2ff3-acfc-42dc-a1d2-f59b09efefc8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "crafideeee-nextjs-new2-2"
template_id = "iq83b9fpyvdnsolrt9n9"
